/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParseRouteImport } from './routes/parse'
import { Route as IndexRouteImport } from './routes/index'

const ParseRoute = ParseRouteImport.update({
  id: '/parse',
  path: '/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parse': typeof ParseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parse': typeof ParseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parse': typeof ParseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parse'
  id: '__root__' | '/' | '/parse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParseRoute: typeof ParseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parse': {
      id: '/parse'
      path: '/parse'
      fullPath: '/parse'
      preLoaderRoute: typeof ParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParseRoute: ParseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
