version: "2.0"

commands:
  up:
    summary: "🚀 Build & run everything"
    command: |
      echo "🐳 Starting development environment..."
      docker compose up --build -d
      echo "✅ Annot[AI]tor Services started!"
      echo "🌐 Annot[AI]tor Frontend: http://localhost:5173"
      echo "🔌 Annot[AI]tor Backend:  http://localhost:3001"
      
  down:
    summary: "🛑 Stop & remove containers"
    command: |
      echo "🛑 Stopping all services..."
      docker compose down -v
  api.console:
    summary: "🔌 Open Rails console"
    command: |
      docker compose exec api rails c
      
  db.shell:
    summary: "🗄️ Open MySQL shell"
    command: |
      docker compose exec db mysql -u rails -ppassword annot_development
      
  processor.start:
    summary: "🔧 Run processor pipeline"
    command: |
      cd processor && dev start $$@
      
  processor.server:
    summary: "🌐 Start processor HTTP server"
    command: |
      cd processor && dev server
      
  processor.shell:
    summary: "🐚 Open processor shell"
    command: |
      cd processor && dev shell
      
  processor.install:
    summary: "📦 Build processor container"
    command: |
      cd processor && dev install
      
  processor.test:
    summary: "🧪 Run processor tests"
    command: |
      cd processor && dev test
      
  test:
    summary: "🧪 Run all tests across all services"
    command: |
      echo "🧪 Running server tests..."
      cd server && dev test
      echo "✅ Server tests completed"
      echo "🧪 Running client tests..."
      cd client && dev test
      echo "✅ Client tests completed"
      echo "🧪 Running processor tests..."
      cd processor && dev test
      echo "✅ Processor tests completed"
      echo "🎉 All tests completed!" 