version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: annot-db
    ports: [ "3306:3306" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: annot_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
    volumes: [ db-data:/var/lib/mysql ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "rails", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s

  api:
    build: ./server
    platform: linux/amd64
    container_name: annot-api
    env_file: [ ./server/.env ]
    volumes: 
      - ./server:/app
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    ports: [ "3001:3001" ]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build: ./client
    platform: linux/amd64
    container_name: annot-web
    env_file: [ ./client/.env.local ]
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports: [ "5173:5173" ]
    depends_on: [ api ]

  processor:
    build: ./processor
    platform: linux/amd64
    container_name: annot-processor
    volumes:
      - ./processor/src:/app/src
      - ./uploads:/data/uploads
    depends_on: [ api ]
    command: ["sleep", "infinity"]

volumes:
  db-data: 